spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 15940898
    driver-class-name: org.postgresql.Driver

  redis:
    host: localhost
    port: 6379
    password: ""
    timeout: 2000
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        max-wait: 1000
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect